//
//  StyleKit.h
//  Bus Ticker
//
//  Created by Brennan Stehling on 9/20/14.
//  Copyright (c) 2014 Bus Ticker. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawDirectionsWithScaleX: (CGFloat)scaleX scaleY: (CGFloat)scaleY;
+ (void)drawStarWithScaleX: (CGFloat)scaleX scaleY: (CGFloat)scaleY starred: (BOOL)starred;
+ (void)drawPickerWithScaleX: (CGFloat)scaleX scaleY: (CGFloat)scaleY;

@end
