//
//  StyleKit.h
//  Bus Ticker
//
//  Created by Brennan Stehling on 9/20/14.
//  Copyright (c) 2014 Bus Ticker. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawDirectionsWithScale: (CGFloat)scale;
+ (void)drawStarWithStarred: (BOOL)starred scale: (CGFloat)scale;
+ (void)drawPickerWithScale: (CGFloat)scale;
+ (void)drawEstimateCircleWithCircleScale: (CGFloat)circleScale scale: (CGFloat)scale;

@end
